### Get list of persons
GET http://localhost:3001/api/persons/

### Delete person 2  
DELETE http://localhost:3001/api/persons/2

### Add person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Justin",
    "number": "323-232-2323"
}